# Generated by Django 3.0.3 on 2021-05-20 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='category',
        ),
    ]
